### PR TITLE
insert, update and replace write option

### PR DESCRIPTION
**Pull request by gbicou**
Allows to choose between insert, update and replace when saving a RDD back to arangodb

### CODE REVIEW

**Comment by joerg84** [comment]
Thanks for the contribution @bicouy0 ! We will review shortly!

**Review by rashtao — CHANGES_REQUESTED** [review]
I would suggest the following:
- modelling the write method with an enumeration, instead of raw strings
- extend WriteOptions construction from SparkConf:  https://github.com/arangodb/arangodb-spark-connector/blob/master/src/main/scala/com/arangodb/spark/package.scala#L68-L82
- add tests

**Comment by gbicou** [comment]
> I would suggest the following:
> 
> * modelling the write method with an enumeration, instead of raw strings

done

> * extend WriteOptions construction from SparkConf:  https://github.com/arangodb/arangodb-spark-connector/blob/master/src/main/scala/com/arangodb/spark/package.scala#L68-L82

this is a per save option so I don't think it should be read from spark configuration

> * add tests

done

**Review by joerg84 — APPROVED** [review]
Thanks, lgtm. @rashtao PTAL

**Review by rashtao — APPROVED** [review]
Thanks!

**Pull request merged**
