### PR TITLE
Enabled streaming for Cursor (Fix for issue #26)

### PR DESCRIPTION
**Pull request by sharwinbobde**
Fix for issue #26

### CODE REVIEW

**Comment by sharwinbobde** [comment]
@mchacki seems like the arangodb enterprise docker image doesn't always start the DB properly for the tests.

**Comment by rashtao** [comment]
Hi @sharwinbobde  ,

thanks for contributing. We are obliged by law to have a signed scanned copy of a Contributor License Agreement (CLA) to be able to accept pull requests to the official ArangoDB repository - even for such small changes.

We use an Apache 2 CLA for ArangoDB and its companion projects, which can be found here: https://www.arangodb.com/documents/cla.pdf
Just fill in the form, sign and send a scanned copy over to cla@arangodb.com

Thank you

**Review by rashtao — APPROVED** [review]

**Comment by sharwinbobde** [comment]
Hey @rashtao the problem is not completely fixed yet.

image

Even If it lazily computes the results they are still backed up on the DB side. So we are sending batches as soon as they are computed in a proper manner but the out-of-memory problem still persists.  To be clear these are only read operations and should not in principle take up any resources once a batch is sent.

This is definitely query data because my buffer sizes don't warrant this behaviour.
```
arangodb --starter.mode single --starter.data-dir $database_path \
        --dbservers.rocksdb.write-buffer-size 10012340 \
        --dbservers.rocksdb.max-write-buffer-number 3 \
        --dbservers.rocksdb.total-write-buffer-size 101234000 \
        --dbservers.rocksdb.dynamic-level-bytes false \
        --dbservers.cache.size 20123400 \
        --all.arangosearch.threads-limit 5 \
        --all.rocksdb.block-cache-size 2056000 \
        --all.rocksdb.enforce-block-cache-size-limit true \
        --all.rocksdb.max-background-jobs 8 \
        --all.server.maintenance-threads 4 \
        --all.server.maximal-threads 8 \
        --all.server.minimal-threads 2
```

**Comment by rashtao** [comment]
As discussed in Slack, for now this PR can be merged.
Please report further problems about memory growth in a new issue, providing steps to reproduce.

**Pull request merged**
