### PR TITLE
Cross compilation scala 2.11 and 2.12

### PR DESCRIPTION
**Pull request by gbicou**
Allow to compile to scala-2.12 with a maven profile : mvn -Pscala-2.12

### CODE REVIEW

**Comment by OmarAyo** [comment]
Hi @bicouy0 

Thanks a lot for your contribution 

For legal reasons we need you to fill out and sign our Contributor License Agreement (CLA). You can scan and email the CLA PDF file to cla@arangodb.com or send it via fax to +49-221-2722999-88.

We are using a Apache 2 CLA for ArangoDB, which can be found here: https://www.arangodb.com/documents/cla.pdf

Best,

**Comment by gbicou** [comment]
Done already in 2017...

**Comment by OmarAyo** [comment]
Hi @bicouy0 

Right, I was able to find it. Thanks again for the contribution

**Comment by gbicou** [comment]
Updated jackson to pass tests

**Comment by BCaxelbecker** [comment]
@bicouy0 i created a new pr for scala 2.12

**Comment by rashtao** [comment]
This library has been now deprecated in favor of the new [ArangoDB Datasource for Apache Spark](https://github.com/arangodb/arangodb-spark-datasource).

**Pull request closed without merging**
